#!/bin/bash

# AFL Formation Templates - Environment Setup
# Generated by Planner Agent for Spec 016

set -e

echo "========================================"
echo "Starting AFL Coaching Board Dev Server"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Navigate to project root
cd "C:\Users\mitch\PycharmProjects\afl_coaching_board"

# Check if node_modules exists, install if needed
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Start Vite dev server
echo -e "${YELLOW}Starting Vite dev server...${NC}"
npm run dev &

# Wait for dev server to be ready
wait_for_service 3000 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Dev Commands:"
echo "  npm run dev    - Start dev server"
echo "  npm run build  - Build for production"
echo "  npm run lint   - Run ESLint"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait
