#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Ball Token with Path feature

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting main service (React + Vite + Three.js)..."
echo ""

# Main service (React frontend)
npm run dev &
MAIN_PID=$!

wait_for_service 3000 "Main (React + Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main:     http://localhost:3000"
echo ""
echo "Tech Stack:"
echo "  - React + TypeScript + Vite"
echo "  - Three.js (@react-three/fiber + @react-three/drei)"
echo "  - Zustand (state management)"
echo "  - Dexie (IndexedDB persistence)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and handle Ctrl+C
trap "echo 'Stopping services...'; kill $MAIN_PID 2>/dev/null; exit" INT TERM
wait
