#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 017: Player Name Labels

set -e

echo "========================================"
echo "Starting Development Environment"
echo "AFL Coaching Board - Player Name Labels"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting main service (React + Vite)..."

# Navigate to project root
cd "$PROJECT_ROOT" || exit 1

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start development server
npm run dev &
DEV_SERVER_PID=$!

# Wait for Vite dev server
wait_for_service 3000 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main (React):  http://localhost:3000"
echo ""
echo "Development Commands:"
echo "  npm run dev      - Start dev server"
echo "  npm run build    - Build for production"
echo "  npm run lint     - Run ESLint"
echo ""
echo "Process IDs:"
echo "  Dev Server: $DEV_SERVER_PID"
echo ""
echo "To stop services:"
echo "  kill $DEV_SERVER_PID"
echo ""
echo "========================================"
