#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 010 - Complete Annotation System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 010: Complete Annotation System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting React Development Server..."
echo ""

# Start Vite dev server
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready on port 5173
wait_for_service 5173 "React App (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  React App:  http://localhost:5173"
echo ""
echo "Development Mode:"
echo "  - Hot Module Replacement (HMR) enabled"
echo "  - TypeScript type checking active"
echo "  - ESLint warnings visible in console"
echo ""
echo "Tech Stack:"
echo "  - React 18 + TypeScript"
echo "  - Three.js (@react-three/fiber, @react-three/drei)"
echo "  - Zustand (state management)"
echo "  - Dexie (IndexedDB persistence)"
echo "  - Tailwind CSS"
echo ""
echo "To stop services: Press Ctrl+C"
echo ""

# Keep script running
wait $VITE_PID
